# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "251bd1f080d3e8566e4fe283bfc7ab9f"
name = "filters-test"
handle = "searchauto-dashboard"
application_url = "https://expect-burlington-booking-ensure.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "vishes-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://expect-burlington-booking-ensure.trycloudflare.com/auth/callback",
  "https://expect-burlington-booking-ensure.trycloudflare.com/auth/shopify/callback",
  "https://expect-burlington-booking-ensure.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
